### ISSUE TITLE
Synchronize arrival at secondary_main

### ISSUE THREAD

**Issue by nategraff-sifive** [sifive/freedom-metal#102]
Hart 0 takes a long time to get to secondary main because it's copying data, zeroing the bss, and running constructors. This makes writing custom `secondary_main`s difficult because you have to contend with race conditions on global variables which aren't yet initialized when secondary harts get there.

We need a mechanism for helping users of metal synchronize arrival at user-defined `secondary_main` implementations.

**Comment by palmer-dabbelt** [comment]
We just shouldn't enter `secondary_main()` until the C library has been initialized.  IIRC our internal code uses the IPI register in the CLINT to handle this, as it's reset on boot.
