### ISSUE TITLE
I2C support?

### ISSUE THREAD

**Issue by drom** [sifive/freedom-metal#113]
Any plans to add I2C support?

**Comment by cylgom** [comment]
... Is anything in the works ? @nategraff-sifive [seems to be working on the hifive1 revb](https://github.com/sifive/freedom-e-sdk/pull/316) and even [added the i2c bare headers recently](https://github.com/sifive/freedom-devicetree-tools/blob/d6a8c41d87d8bfa4f931b32d31767fdb1c64c596/bare_header/sifive_i2c0.h) in the devicetree-tools repo. Should I give up writing [my own broken driven](https://github.com/cylgom/freedom-metal/blob/i2c/src/drivers/sifive_i2c0.c) ?
