### ISSUE TITLE
Conventions used in metal - questions

### ISSUE THREAD

**Issue by ghost** [sifive/freedom-metal#118]
1) Whitespace & Tabs - what is the style here?

tabs seem to be 4, but should it be spaces or tabs?

2) Do you have a well known "named style" to follow?

3) What thought has been given to c style enforcement?

Would ".clangformat" be useful? it is a bit more "modern" then other solutions.
Reference: https://clang.llvm.org/docs/ClangFormat.html
Reference: https://www.kernel.org/doc/html/latest/process/clang-format.html

Plugins exist for several popular editors

Eclipse:  https://marketplace.eclipse.org/content/cppstyle
VIM: https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/clang-format.py
EMACS: https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/clang-format.el
VSCODE: https://marketplace.visualstudio.com/items?itemName=xaver.clang-format

4) Do you have a travis or similar automation system in place tied to github pull requests?

For example some other open packages I've been involved with use this as part of the pull request validation. Effectively, when a pull request is created travis auto-runs a series of tests (including for example format checks) if all goes well - travis votes "approved" auto-magically.

It's controlled by a simple '.travis.yml' file in the root directory.

Example:  https://github.com/openthread/openthread/blob/master/.travis.yml

An example of the number of tests and details you can get
https://travis-ci.org/openthread/openthread/builds/541318541?utm_source=github_status&utm_medium=notification

**Comment by nategraff-sifive** [comment]
Hi Duane,

We should enforce a style guide, we'll keep this issue as a way of tracking that. We can also hook up a GitHub check to enforce the style on new PRs.

We currently run regression in automation on an internal CI system. Providing an externalized regression isn't going to be achievable for quite a while though.
