### ISSUE TITLE
__metal_driver_sifive_fe310_g000_pll_init() incorrectly tests PLL_SEL

### ISSUE THREAD

**Issue by danak6jq** [sifive/freedom-metal#210]
File sifive_fe310-g000_pll.c, lines 167-169 are:

```
    /* If we're running off of the PLL, switch off before we start configuring it*/
    if((__METAL_ACCESS_ONCE(pllcfg) & PLL_SEL) == 0)
        __METAL_ACCESS_ONCE(pllcfg) &= ~(PLL_SEL);
```

which does not appear to make sense. If PLL_SEL is already 0 (the test in the 'if' statement), there's no point in clearing it. If it *is* set (unlikely since this is __metal_driver_sifive_fe310_g000_pll_init()) then it will remain set.

Either this needs to be corrected to test for PLL_SEL non-zero or removed.

**Comment by nategraff-sifive** [comment]
Thanks for catching this @danak6jq!
