### ISSUE TITLE
build.make is not on Sync up with scripts/autoconf_wrapper

### ISSUE THREAD

**Issue by RajeshVaradharajan** [sifive/freedom-metal#212]
autoconf_wrapper is taking 5 inputs as arguments from its previous version which was taking 7 arguments.

build.wake is not in sync with the latest changes in the autoconf_wrapper and still providing 7 arguments and the scripts fails.

**Comment by nategraff-sifive** [comment]
They look to be in sync to me on `v201908-branch` and `master`. Nothing else is actively supported, so I'm not sure where the discrepancy is. Feel free to re-open with a version where they're failing.

**Comment by RajeshVaradharajan** [comment]
In v201908, build.wake calls ./scripts/autoconf_wrapper with 7 input args. 

In master, build.wake calls ./scripts/autoconf_wrapper with 5 input args. But the script still expects 7 input args.
 
<img width="926" alt="Screen Shot 2020-01-09 at 11 25 03 AM" src="https://user-images.githubusercontent.com/39745980/72041971-05803d00-32d3-11ea-994a-81a9ff4548b0.png">

<img width="1196" alt="Screen Shot 2020-01-09 at 11 25 42 AM" src="https://user-images.githubusercontent.com/39745980/72042088-63148980-32d3-11ea-8dc2-67389d678c0a.png">

So i end up with the following error when i use the freedom-metal master

+ set -e
+ '[' 5 -ne 7 ']'
+ echo 'Illegal number of parameters'
Illegal number of parameters
+ exit 1

**Comment by richardxia** [comment]
I decided to take a look at this as well, and I think I see the discrepancy that @RajeshVaradharajan is pointing out.

On master, `autoconf_wrapper`'s `if` statement at the top seems to check for 7 arguments being passed in:

https://github.com/sifive/freedom-metal/blob/c6cac684d22772c0619d2b89d8b9cf9addf87c33/scripts/autoconf_wrapper#L5

despite the fact that only five appear to actually be used:

https://github.com/sifive/freedom-metal/blob/c6cac684d22772c0619d2b89d8b9cf9addf87c33/scripts/autoconf_wrapper#L10-L14

`build.wake` only seems to pass in 5 arguments:

https://github.com/sifive/freedom-metal/blob/c6cac684d22772c0619d2b89d8b9cf9addf87c33/build.wake#L90-L97

and although those are the only five that are actually used, the fact that we don't pass in two additional arguments causes `autoconf_wrapper` to abort early.
