### ISSUE TITLE
configure_pll() might be in a rush to test PLL_LOCK

### ISSUE THREAD

**Issue by danak6jq** [sifive/freedom-metal#213]
Around line 293 of src/drivers/sifive_fe310-g000_pll.c:

```
    /* Wait for PLL to lock */
    while((__METAL_ACCESS_ONCE(pllcfg) & PLL_LOCK) == 0) ;
```

Section 6.5 of the FE310-G002 Manual 1p4 says:

> The PLL provides a lock signal which is set when the PLL has achieved lock, and which can be
> read from the most-significant bit of the pllcfg register. The PLL requires up to 100 μs to
> regain lock once enabled, and the lock signal will not necessarily be stable during this initial lock
> period so should only be interrogated after this period.

So this code seems to be a little aggressive, not waiting 100uS before entering the wait loop. I have not confirmed why yet, but a test program that configures the PLL to 320MHz infrequently hangs apparently when setting the PLL. Hardware is SparkFun Red-V with R8 corrected to 100 ohms (power supply filter for PLLVDD).

I appreciate a 100uS delay might be hard to arrange here in Metal given it seems to depend on other hardware configuration (LFROSC?) or CPU clock rate.

**Comment by nategraff-sifive** [comment]
Hmm, it's definitely a bit tricky to Correctly™️ arrange a 100 us delay. For now, it might be enough to know that the LFROSC rate is 32768 Hz on all supported boards with the FE310-G002 and just wait for four ticks.

**Comment by nategraff-sifive** [comment]
Here's a branch which adds a 122 usec delay by assuming that mtime is running at 32768 Hz: https://github.com/sifive/freedom-metal/tree/pll-lock-race

I can probably pull in the mtime timebase from the devicetree with a bit more work, but for now if you'd like to try running at 320 MHz let me know what you see!

**Comment by danak6jq** [comment]
> Here's a branch which adds a 122 usec delay by assuming that mtime is running at 32768 Hz: https://github.com/sifive/freedom-metal/tree/pll-lock-race
> 
> I can probably pull in the mtime timebase from the devicetree with a bit more work, but for now if you'd like to try running at 320 MHz let me know what you see!

The Sparkfun RED-V does have a 32768Hz clock that appears to work - I'll pull the branch and give it a try. Thank you for looking at this!

> Hmm, it's definitely a bit tricky to Correctly™️ arrange a 100 us delay.

"I feel your pain" :-) Especially since a busy-wait loop would be clocked by the PLL and thus indeterminate.

**Comment by danak6jq** [comment]
I'm realizing I'm not sure how to use this branch with the Windows Eclipse workspace that I'm using. I downloaded the branch, and used Project > Properties > Freedom Studio > SDK... to change the METAL_SOURCE_PATH to the top of the branch dir. Eclipse attempts to build but becomes unhappy with 17 errors like below. Any pointers to docs or wisdom on how to do this?

In file included from C:/Users/Dana/Downloads/freedom-metal-pll-lock-race/freedom-metal-pll-lock-race/src/drivers/riscv_plic0.c:12:
C:/Users/Dana/Downloads/freedom-metal-pll-lock-race/freedom-metal-pll-lock-race/src/drivers/riscv_plic0.c: In function '__metal_plic0_claim_interrupt':
C:/Users/Dana/Downloads/freedom-metal-pll-lock-race/freedom-metal-pll-lock-race/src/drivers/riscv_plic0.c:22:43: error: 'METAL_RISCV_PLIC0_CONTEXT_BASE' undeclared (first use in this function); did you mean 'METAL_RISCV_PLIC0_PENDING_BASE'?
         (__metal_io_u32 *)(control_base + METAL_RISCV_PLIC0_CONTEXT_BASE +
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Dana/Downloads/freedom-metal-pll-lock-race/freedom-metal-pll-lock-race/metal/io.h:8:47: note: in definition of macro '__METAL_ACCESS_ONCE'
 #define __METAL_ACCESS_ONCE(x) (*(__typeof__(*x) volatile *)(x))

**Comment by nategraff-sifive** [comment]
My first thought is to make sure you using the latest master of freedom-e-sdk and just update the freedom-metal submodule.

**Comment by danak6jq** [comment]
OK, I did:
`git clone --branch master --single-branch --recursive https://github.com/sifive/freedom-e-sdk.git`

and used that E SDK  to create a new project, now I can point the METAL_SOURCE_PATH at the PLL lock race wad and it builds _woot_

However, I get stuck at an actual clock rate change (i.e. not 16MHz which is a special case of PLL_BYPASS), because:

```
unsigned long long __metal_driver_cpu_mtime_get(struct metal_cpu *cpu) {
    unsigned long long time = 0;
    struct metal_interrupt *tmr_intc;
    struct __metal_driver_riscv_cpu_intc *intc =
        (struct __metal_driver_riscv_cpu_intc *)
            __metal_driver_cpu_interrupt_controller(cpu);

    if (intc) {
        tmr_intc = intc->metal_int_table[METAL_INTERRUPT_ID_TMR].sub_int;
        if (tmr_intc) {
            tmr_intc->vtable->command_request(tmr_intc, METAL_TIMER_MTIME_GET,
                                              &time);
        }
    }
    return time;
}
```
finds intc->metal_int_table[] to be apparently uninitialized (zeroes), so mtime is returned as 0; time stands still, ref:

__metal_driver_cpu_mtime_get() at riscv_cpu.c:637 0x20013372	
metal_cpu_get_mtime() at cpu.h:97 0x2001610c	
configure_pll() at sifive_fe310-g000_pll.c:314 0x20014782	
__metal_driver_sifive_fe310_g000_pll_set_rate_hz() at sifive_fe310-g000_pll.c:353 0x200148e6	
metal_clock_set_rate_hz() at clock.h:131 0x20016070	

Any ideas?

**Comment by nategraff-sifive** [comment]
Oof, that's right, `mtime` comes out of the CLINT, and the interrupt tables aren't set up here.

Second attempt: I'll try using the technique in `src/synchronize_harts.c` to directly call the CLINT/CLIC drivers to read the value of mtime.

**Comment by danak6jq** [comment]
I'm guessing the 100uS delay is intended to allow the lock indication to become false as the PLL starts changing frequency - I'd expect the lock to be true at the instant the new frequency is programmed, and take some time to become false as the loop starts bouncing. If this is correct, the downside of waiting the 100uS is that the PLL frequency is indeterminate for some time after returning - if code depends on instruction timing, it will be incorrect until the PLL is locked again. While this probably doesn't result in a fatal error by itself, it could create a _severely_ difficult bug.

**Comment by nategraff-sifive** [comment]
Branch updated, give it a whirl!

**Comment by danak6jq** [comment]
OK - that's behaving as expected. I stopped in configure_pll() and confirmed the mtime value looks sane (not stuck). Running a dead simple benchmark (time iterations of mrand48() with the RTC) and it's behaving exactly as expected while switching between 288MHz and 320MHz each trial, as well as 2MHz and 320MHz. I'll leave it flipping 288/320MHz for a while (that's ~33 clock changes/sec) and verify it doesn't hang.

**Comment by danak6jq** [comment]
Thanks for fixing this.
