### ISSUE TITLE
There is a problem in metal_get_memory_from_address API

### ISSUE THREAD

**Issue by reclusejack** [sifive/freedom-metal#378]
Hi ~

When testing the big memory region, we found there is a problem in the metal_get_memory_from_address function.

The fail case is as following.

input parameter "address" = 0x8000_0000 and the start address of memory is 0x8000_0000 and the size is 0x8000_0000

The upper_bound value will be 0x8000_0000 + 0x8000_0000 and get a overflow which is not we expected.

 14         if ((address >= lower_bound) && (address < upper_bound)) {
 15             return mem;
 16         }

**Comment by e-puerto** [comment]
It is a typical overflow issue. Fix are merge into master.

**Comment by reclusejack** [comment]
Thanks for fixing this issue.
